# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dummy.proto',
  package='dummy',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x64ummy.proto\x12\x05\x64ummy\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"C\n\x07UserRes\x12\x0e\n\x06nameOf\x18\x01 \x01(\t\x12\r\n\x05grade\x18\x02 \x01(\x03\x12\x0c\n\x04roll\x18\x03 \x01(\x03\x12\x0b\n\x03\x65rr\x18\x04 \x01(\t2;\n\x07Metrics\x12\x30\n\x0fGetMockUserData\x12\x0b.dummy.User\x1a\x0e.dummy.UserRes\"\x00\x62\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='dummy.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dummy.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=42,
)


_USERRES = _descriptor.Descriptor(
  name='UserRes',
  full_name='dummy.UserRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nameOf', full_name='dummy.UserRes.nameOf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grade', full_name='dummy.UserRes.grade', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roll', full_name='dummy.UserRes.roll', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err', full_name='dummy.UserRes.err', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserRes'] = _USERRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:dummy.User)
  })
_sym_db.RegisterMessage(User)

UserRes = _reflection.GeneratedProtocolMessageType('UserRes', (_message.Message,), {
  'DESCRIPTOR' : _USERRES,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:dummy.UserRes)
  })
_sym_db.RegisterMessage(UserRes)



_METRICS = _descriptor.ServiceDescriptor(
  name='Metrics',
  full_name='dummy.Metrics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMockUserData',
    full_name='dummy.Metrics.GetMockUserData',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USERRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METRICS)

DESCRIPTOR.services_by_name['Metrics'] = _METRICS

# @@protoc_insertion_point(module_scope)
