# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dummy_pb2 as dummy__pb2


class MetricsStub(object):
    """Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMockUserData = channel.unary_unary(
                '/dummy.Metrics/GetMockUserData',
                request_serializer=dummy__pb2.User.SerializeToString,
                response_deserializer=dummy__pb2.UserRes.FromString,
                )


class MetricsServicer(object):
    """Service Definition
    """

    def GetMockUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMockUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMockUserData,
                    request_deserializer=dummy__pb2.User.FromString,
                    response_serializer=dummy__pb2.UserRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dummy.Metrics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Metrics(object):
    """Service Definition
    """

    @staticmethod
    def GetMockUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dummy.Metrics/GetMockUserData',
            dummy__pb2.User.SerializeToString,
            dummy__pb2.UserRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
